### ISSUE TITLE
Slack Invites Coming From Me

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.github.io#11]
Not sure how much we care (feel free to backlog this) but the invites come from me because I created the API key that Heroku is using.

We'd have to sign up admin@devanooga.com (or whatever) for Slack and have it generate the token to be used (during that we move the Heroku service too, or not, I don't care that much if it's on mine, it's a free slot).

**Comment by StrangeWill** [comment]
![image](https://cloud.githubusercontent.com/assets/1322565/22393209/f1862b64-e4d0-11e6-9fbe-37cb8c7756f1.png)

**Comment by brb3** [comment]
Hmm, yea. admin@devanooga.com is what I'm using for everything (just redirects to bobby@brb3.org). It would be nice to have it come from that address. I'll setup a heroku account with that email address.

**Comment by agarzola** [comment]
I feel like it’s appropriate for your account to be the one to welcome every single user that signs up with this. :)

**Comment by StrangeWill** [comment]
> I'll setup a heroku account with that email address.

It needs to be a Slack account.

**Comment by brb3** [comment]
Oh I see, ok. I'll do that now.

**Comment by StrangeWill** [comment]
![image](https://cloud.githubusercontent.com/assets/1322565/22393614/0ece3b2e-e4d8-11e6-9f45-1895ff256796.png)
👍
