### ISSUE TITLE
Issue management

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.github.io#20]
If we end up seriously developing this/other projects, a more serous management system would rock. I haven't played with projects in Github (do those span multiple repos?), but I _have_ been a fan of Waffle.io.

Opinions?

**Comment by brb3** [comment]
I really don't like github's projects. As far as I know they are just for a single repo -- it doesn't really make sense. They should be organization-based, IMO.

I'm cool with waffle.io, I've used it a bit in the past and it worked fine. I'll setup an account on Waffle.io now, and we can move to something else if anyone has a better/preferred PMS.

**Comment by brb3** [comment]
Ok, setup a waffle.io board here: https://waffle.io/devanooga/devanooga.github.io

I'll close this issue for now. We can revisit in the future if necessary.
