### ISSUE TITLE
Disable Github Pages

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.github.io#21]
Got this error in my e-mail:

>The page build failed with the following error:
>
>unable to build page. Please try again later.
>
>For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/troubleshooting-jekyll-builds
>
>If you have any questions you can contact us by replying to this email.

We don't have a gh-pages branch, and I don't see a way to turn off the build process, grr...

**Comment by brb3** [comment]
We should probably also change the repo name to "website" or something. Anyone opposed to that?

**Comment by StrangeWill** [comment]
I'm fine with that, may break integration with Netlify or something though, so we need to go check those.

**Comment by brb3** [comment]
Resolved in #23 
Creating a separate issue for renaming the repo.
