### ISSUE TITLE
Member Page

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.github.io#27]
At least get some basic layout/data format stuff going + update the readme on how to either:

1. Make a PR
2. Make an issue to update it

^ Not everyone is savvy with Git, or has the time to learn it + github, so accessibility would be nice IMO.

**Comment by agarzola** [comment]
I like fallbacks. Fallbacks are good.

**Comment by StrangeWill** [comment]
Add `admin: false/true` flag for the membership profile.


_Totally_ accept PRs where people set this to true.

**Comment by brb3** [comment]
I like the `role: admin` idea personally.

**Comment by agarzola** [comment]
This is probably overthinking it, but not knowing what other roles there might be: what if someone has multiple roles? If that were ever the case, which of these do we want:

```
role: admin, other_role, yet_another_role
```

```
admin: true
other_role: true
yet_another_role: true
```

I personally have no strong preference, but but the second one seems clearer at a glance, both when looking at a conditional statement. In any case, I think it’s worthwhile to consider this, if only briefly.

**Comment by brb3** [comment]
Ah, that's a really good point @agarzola .
Hmm, ok. Well I guess we should go with `admin: (bool)`. That's a bit more flexible, as we might have something like:
```
admin: true
event_organizer: true
```
Or something like that, ya know?

**Comment by StrangeWill** [comment]
Will probably slip them under a `roles` section

```
roles:
  admin: true
  event_organizer: true
```

**Comment by agarzola** [comment]
I wasn't aware that front matter can handle nested properties like that. That sounds ideal.

**Comment by StrangeWill** [comment]
I'm pretty sure it can... but then again I'm totally unfamiliar with Jekyll so I may be wrong and making awful recommendations.
