### ISSUE TITLE
Menu breaks when adding pages

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.github.io#37]
Naturally, right? Now that we have a contact page, the menu has now outgrown the space available to it. This is easily addressed with a larger breakpoint for it (so that it’s not expanded until there’s space for the whole thing), but then we’ll have this issue again later when we add the channels page.

I’m working on allowing the header wrapper to stretch a bit wider so that it can accommodate plenty of menu items at its widest. But I’d like to hear your ideas on an idea I have to address the actual problem.

I propose we add a property to every top-level page’s front matter; something like `menu_group`, for instance, with an integer value (starting at 1). Say we have two groups, with whatever we determine to be the most important menu items showing a value of `1` and everything else show a value of `2`. As the viewport expands and enough space becomes available for group 1 to be shown (plus a _More_ link much like the small screen _Menu_ link), we expand only those items. The items belonging to group 2 are still collapsed under that _More_ link.

Likewise, once there is enough space to show all of the menu items, everything is expanded and no _More_ or _Menu_ link is shown.

Does that make sense?

**Comment by brb3** [comment]
I like that idea.

Is there a way to set a default for front-matter? So, if the page doesn't have a value it's defaulted to "0" or something (0 meaning "don't even show it in the menu")?

**Comment by agarzola** [comment]
That should be relatively easy to do in the loop from the navigation template, yeah. Good thinking!

**Comment by StrangeWill** [comment]
Oh I love the grouping/prioritization idea.

**Comment by agarzola** [comment]
Here’s what I’m thinking:

**Group 1 (most important)**
- Code of conduct
- Channels
- Open source
- Join us (slack)

**Group 2**
- Members
- Contact us

Does that make sense?

**Comment by agarzola** [comment]
@brb3 Sorry, I edited just after you gave the thumbs up.

**Comment by brb3** [comment]
I'm still fine with that. I'd see Channels, Open Source, and Join Us as the three most important items.
