### ISSUE TITLE
Write CoC Page

### ISSUE THREAD

**Issue by brb3** [devanooga/devanooga.github.io#4]
Need a Code of Conduct

**Comment by agarzola** [comment]
How specific do we want this to be? I’ve looked at some templates and found some of them to be openly hostile towards vaguely defined “privileged groups.” Also defining harassment too broadly (unwelcome comments regarding a person’s “lifestyle choices,” among which figure food, drugs, and employment). See example: http://todogroup.org/opencodeofconduct/

But I think it’s not a bad idea to start there and remove some of the excessive bits?

**Comment by brb3** [comment]
@agarzola I started a PR with a rough outline. Feel free to propose changes. 

I want it to be, roughly something like: "Attack ideas, not people. We are not a safe space. Be nice-ish, you might get banned"
